# Generated by Django 4.0.3 on 2022-04-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Familiares',
        ),
    ]
